"""add  user relations from course class

Revision ID: 6f432e0b8d9c
Revises: cfa7bd56922b
Create Date: 2022-05-19 23:41:20.003074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f432e0b8d9c'
down_revision = 'cfa7bd56922b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'user_id')
    # ### end Alembic commands ###
